#!/bin/sh
if [[ -z "${GITHUB_USERS}" ]]; then
  echo "Must set GITHUB_USERS"
  exit 1
fi
DIR=/user/.ssh
mkdir -p $DIR
chmod 700 $DIR
touch $DIR/authorized_keys
chmod 600 $DIR/authorized_keys
sed -i '/^#### GITHUB START/,/GITHUB END ####/d' $DIR/authorized_keys
echo "#### GITHUB START ####" >> $DIR/authorized_keys
ARR=$(echo ${GITHUB_USERS} | tr "," "\n")
for USER in $ARR; do

  echo "Adding keys for $USER"


  echo "#### $USER ####" >> $DIR/authorized_keys
  curl --silent https://github.com/$USER.keys >> $DIR/authorized_keys
  echo "#### END $USER ####" >> $DIR/authorized_keys

done
echo "#### GITHUB END ####" >> $DIR/authorized_keys
